---
actions:
  1:
    action: delete_indices
    description: Delete antarctica indices older than 4 days
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: false
    filters:
    - filtertype: pattern
      kind: prefix
      value: antarctica-
      exclude:
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 4
      exclude:
  2:
    action: delete_indices
    description: Delete spam indices by name
    options:
      ignore_empty_list: True
      timeout_override:
      continue_if_exception: False
      disable_action: false
    filters:
    - filtertype: pattern
      kind: regex
      value: '^(b|f|l|s|d|c|l|m|x|d).*$'
